name: React Performance Monitor CI with Playwright

on:
  push:
    paths:
      - 'react-performance-monitor/**'
      - '.github/workflows/**'
    branches: [main]

  pull_request:
    paths:
      - 'react-performance-monitor/**'
      - '.github/workflows/**'
    types: [opened, synchronize, reopened]

jobs:
  react-app-tests:
    name: React Performance Monitor  Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: react-performance-monitor

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests with Playwright
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: ${{ secrets.SONAR_ORGANIZATION }}
          token: ${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}